config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: [:show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
before_action :set_cocktail, only: [:show, :destroy]

  def index
    @name = params[:search]
    if @name.nil?
      @cocktails = Cocktail.all
    else
     @cocktails = Cocktail.where(name: @name)
    end
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail.destroy
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :search)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="#">
    <img src="https://image.flaticon.com/icons/png/512/168/168558.png" />
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">All cocktails</a>
      </li>
      <li>
        <div class = "p-20">
          <%= simple_form_for(:search, url: cocktails_path, method: "GET", html: { class: 'form-inline p-60 container' }) do |f| %>
            <%= f.input "", required: false, input_html: {value: "", placeholder: "search"} %>
            <%= f.submit "Search", class: "btn btn-success" %>
          <% end %>
        </div>
    </ul>
  </div>
</div>
<h1> All the best cocktails </h1>

<ul class = "d-flex align-items-center  justify-content-center">
      <% @cocktails.each do |cocktail| %>
        <li class = "card item" style="margin: 15px ; height: 400px" > <%= link_to cocktail.name, cocktails_path%>
            <img src="<%=cocktail.image%>" alt="" width = '400px' height = '300px'>
        <% cocktail.doses.each do | dose | %>
            <p> <%= "#{dose.description} : #{dose.ingredient.name}"%></p>
          <% end %>
        </li>
      <%end%>
</ul>

app/views/cocktails/new.html.erb
<h1> Create your super cocktail</h1>

<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>
<img src="<%=@cocktail.image%>" alt="">
<ul>
  <% @cocktail.doses.each do | dose | %>
  <li> <%= "#{dose.description} : #{dose.ingredient.name}"%></li>
  <% end %>
</ul>

app/views/doses/new.html.erb
<div class="container">
  <h1> Create your delicious cocktail</h1>
  <div class = "card">
    <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.input :description %>
      <%= f.association :ingredient %>
      <%= f.button :submit %>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>